# Generated by Django 4.2.16 on 2025-01-02 18:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import yuk.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Advertisement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('status', models.CharField(choices=[('P', 'Pending'), ('A', 'Accepted')], max_length=1)),
                ('date', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Shipper',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profilePicture', models.ImageField(default='profile.png', upload_to='yuk/profile_pictures')),
                ('phone', models.CharField(max_length=11, validators=[yuk.models.phone_start_with_0])),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('origin', models.CharField(max_length=200)),
                ('destination', models.CharField(max_length=200)),
                ('distance', models.FloatField()),
                ('estimated_time', models.FloatField()),
                ('advertisement', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='yuk.advertisement')),
            ],
        ),
        migrations.CreateModel(
            name='Cargo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.FloatField()),
                ('type', models.CharField(max_length=200)),
                ('value', models.FloatField()),
                ('dimension', models.CharField(max_length=200)),
                ('special_instructions', models.TextField(blank=True)),
                ('advertisement', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='yuk.advertisement')),
            ],
        ),
        migrations.AddField(
            model_name='advertisement',
            name='shipper',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='yuk.shipper'),
        ),
    ]
