# Generated by Django 4.2.16 on 2025-01-02 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yuk', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='advertisement',
            name='freight',
            field=models.IntegerField(null=True),
        ),
    ]
