# Generated by Django 4.2.16 on 2025-01-02 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yuk', '0002_advertisement_freight'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advertisement',
            name='status',
            field=models.CharField(choices=[('P', 'در حال انتظار'), ('A', 'پذیرفته شده')], max_length=1),
        ),
    ]
