# Generated by Django 4.2.16 on 2025-01-17 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yuk', '0003_alter_advertisement_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='advertisement',
            options={'ordering': ['date']},
        ),
        migrations.AddField(
            model_name='route',
            name='dest_city',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='route',
            name='origin_city',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='advertisement',
            name='status',
            field=models.CharField(choices=[('P', 'در حال انتظار'), ('A', 'پذیرفته شده')], default='P', max_length=1),
        ),
    ]
