# Generated by Django 4.2.16 on 2025-01-23 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yuk', '0004_alter_advertisement_options_route_dest_city_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='advertisement',
            options={'ordering': ['-date']},
        ),
        migrations.AlterField(
            model_name='advertisement',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='route',
            name='distance',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='route',
            name='estimated_time',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='shipper',
            name='profilePicture',
            field=models.ImageField(default='yuk_pictures/profile.png', upload_to='yuk_pictures/'),
        ),
    ]
