# Generated by Django 4.2.16 on 2025-01-02 19:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import yol.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('yuk', '0003_alter_advertisement_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Waybill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pickup_date', models.DateField()),
                ('delivery_date', models.DateField(blank=True)),
                ('status', models.CharField(choices=[('S', 'در حال بارگیری'), ('T', 'در حال حمل'), ('R', 'گزارش'), ('A', 'تحویل بار')], max_length=1)),
                ('advertisemet', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='yuk.advertisement')),
            ],
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('type', models.CharField(choices=[('A', 'تصادف'), ('R', 'سرقت از محموله'), ('B', 'خرابی خودروی باربری'), ('W', 'آب و هوای نامساعد')], max_length=1)),
                ('description', models.TextField()),
                ('status', models.CharField(choices=[('W', 'در حال پیگیری گزارش'), ('S', 'رفع گزارش و ادامه مسیر'), ('N', 'عدم توانایی در ادامه حمل بار')], max_length=1)),
                ('Waybill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='yol.waybill')),
            ],
        ),
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profilePicture', models.ImageField(default='profile.png', upload_to='yuk/profile_pictures')),
                ('phone', models.CharField(max_length=11, validators=[yol.models.phone_start_with_0])),
                ('licenseCode', models.IntegerField(max_length=10)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.CharField(max_length=200)),
                ('type', models.CharField(choices=[('V', 'وانت بار'), ('N', 'وانت نیسان'), ('K', 'کامیونت'), ('T', 'تریلی')], max_length=1)),
                ('year', models.IntegerField()),
                ('capacity', models.IntegerField()),
                ('driver', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='yol.driver')),
            ],
        ),
    ]
