# Generated by Django 4.2.16 on 2025-01-02 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yol', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driver',
            name='licenseCode',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='waybill',
            name='delivery_date',
            field=models.DateTimeField(default=0),
        ),
        migrations.AlterField(
            model_name='waybill',
            name='pickup_date',
            field=models.DateTimeField(),
        ),
    ]
