# Generated by Django 4.2.16 on 2025-01-23 17:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('yol', '0003_alter_report_date_alter_waybill_delivery_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='waybill',
            name='driver',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='yol.driver'),
        ),
        migrations.AlterField(
            model_name='car',
            name='capacity',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='car',
            name='model',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='car',
            name='type',
            field=models.CharField(blank=True, choices=[('V', 'وانت بار'), ('N', 'وانت نیسان'), ('K', 'کامیونت'), ('T', 'تریلی')], max_length=1),
        ),
        migrations.AlterField(
            model_name='car',
            name='year',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='driver',
            name='profilePicture',
            field=models.ImageField(default='yol_pictures/profile.png', upload_to='yol_pictures/'),
        ),
        migrations.AlterField(
            model_name='report',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='waybill',
            name='pickup_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='waybill',
            name='status',
            field=models.CharField(choices=[('W', 'پذیرفته شده توسط راننده'), ('S', 'در حال بارگیری'), ('T', 'در حال حمل'), ('R', 'گزارش'), ('A', 'تحویل بار')], default='W', max_length=1),
        ),
    ]
