# Generated by Django 4.2.16 on 2025-01-23 17:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('yol', '0004_waybill_driver_alter_car_capacity_alter_car_model_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='waybill',
            old_name='advertisemet',
            new_name='advertisement',
        ),
    ]
