# Generated by Django 4.2.16 on 2025-01-23 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yol', '0005_rename_advertisemet_waybill_advertisement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='waybill',
            name='delivery_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
