# Generated by Django 4.2.16 on 2025-01-24 18:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('yol', '0006_alter_waybill_delivery_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='status',
            field=models.CharField(choices=[('W', 'در حال پیگیری گزارش'), ('S', 'رفع گزارش و ادامه مسیر'), ('N', 'عدم توانایی در ادامه حمل بار')], default='W', max_length=1),
        ),
        migrations.AlterField(
            model_name='waybill',
            name='driver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='yol.driver'),
        ),
        migrations.AlterField(
            model_name='waybill',
            name='status',
            field=models.CharField(choices=[('W', 'پذیرفته شده توسط راننده'), ('S', 'در حال بارگیری'), ('T', 'در حال حمل'), ('R', 'گزارش'), ('A', 'تحویل بار'), ('N', 'ناتمام')], default='W', max_length=1),
        ),
    ]
