# Generated by Django 4.2.16 on 2025-01-24 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yol', '0007_alter_report_status_alter_waybill_driver_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='licensePlate',
            field=models.CharField(blank=True, max_length=9, null=True),
        ),
    ]
